In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/amazon-product-reviews-dataset")

print("Path to dataset files:", path)

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /home/codespace/.cache/kagglehub/datasets/yasserh/amazon-product-reviews-dataset/versions/1

In [2]:
# Library for file manipulation
import pandas as pd
import numpy as np
import pandas

In [3]:
# Data visualization
import seaborn as sns
import matplotlib.pylab as pl
import matplotlib as m
import matplotlib as mpl
import matplotlib.pyplot as plt
import plotly.express as px
from matplotlib import pyplot as plt

In [4]:
import os
for file in os.listdir(path):
    print(file)

7817_1.csv

In [5]:
# Database
file_path = f"{path}/7817_1.csv"
df = pd.read_csv(file_path)

# Viewing dataset
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,This is not the same remote that I got for my ...,I would be disappointed with myself if i produ...,NaN,NaN,GregAmandawith4,NaN,NaN,4 ounces
1593,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I have had to change the batteries in this rem...,Battery draining remote!!!!,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1594,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"Remote did not activate, nor did it connect to...",replacing an even worse remote. Waste of time,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1595,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,It does the job but is super over priced. I fe...,Overpriced,NaN,NaN,Meg Ashley,NaN,NaN,4 ounces
1596,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I ordered this item to replace the one that no...,I am sending all of this crap back to amazon a...,NaN,NaN,DIANE K,NaN,NaN,4 ounces

In [6]:
# Step 1: Fill NaNs in rating with 0 for safety
df['reviews.rating'] = df['reviews.rating'].fillna(0)

# Step 2: Sort by product name, username, and rating (highest first)
df_sorted = df.sort_values(by=['name', 'reviews.username', 'reviews.rating'], ascending=[True, True, False])
df_sorted = df_sorted[df_sorted['reviews.rating'] > 0]

# Step 3: Drop duplicates – keep only first review per user per product
df_deduped = df_sorted.drop_duplicates(subset=['name', 'reviews.username'], keep='first')

# Optional: Reset index
df_deduped = df_deduped.reset_index(drop=True)

In [7]:
df = df_deduped

In [8]:
import json
from datetime import datetime

# Function to get latest EUR price or fallback to USD
def extract_clean_price(prices_data):
    try:
        prices = json.loads(prices_data) if isinstance(prices_data, str) else prices_data
        # Try EUR first
        eur_prices = [p for p in prices if p.get('currency') == 'EUR']
        if eur_prices:
            eur_prices.sort(key=lambda x: datetime.fromisoformat(x['dateAdded'].replace('Z', '')), reverse=True)
            return eur_prices[0].get('amountMin')

        # Fallback to USD
        usd_prices = [p for p in prices if p.get('currency') == 'USD']
        if usd_prices:
            usd_prices.sort(key=lambda x: datetime.fromisoformat(x['dateAdded'].replace('Z', '')), reverse=True)
            return usd_prices[0].get('amountMin')

        return None
    except Exception as e:
        print(f"Oopsie in row: {e}")
        return None

# Replace the original 'prices' column with the clean value
df['prices'] = df['prices'].apply(extract_clean_price)

In [9]:
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2017-03-27T20:52:11Z,2017-08-13T08:28:47Z,NaN,NaN,alexavoiceremoteforamazonechoechodot/b01e9ahu8q,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,Remote is a great addition......I Have two ech...,Remote is a great addition.,NaN,NaN,BFI66,NaN,NaN,4 ounces
1,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2017-03-27T20:52:11Z,2017-08-13T08:28:47Z,NaN,NaN,alexavoiceremoteforamazonechoechodot/b01e9ahu8q,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,The remote seems to function as the previous g...,No Magnetic Holster - But Remote Is Same,NaN,NaN,Jeffrey C Drywater,NaN,NaN,4 ounces
2,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2017-03-27T20:52:11Z,2017-08-13T08:28:47Z,NaN,NaN,alexavoiceremoteforamazonechoechodot/b01e9ahu8q,...,2.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"As good as the Echo is, the Echo Voice Remote ...","Has Trouble Understanding Commands, Volume Con...",NaN,NaN,Jeffrey N. Fritz,NaN,NaN,4 ounces
3,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2017-03-27T20:52:11Z,2017-08-13T08:28:47Z,NaN,NaN,alexavoiceremoteforamazonechoechodot/b01e9ahu8q,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,Worked great for a few weeks then completely s...,Dead after 3 weeks,NaN,NaN,Shain Mercer,NaN,NaN,4 ounces
4,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2017-03-27T20:52:11Z,2017-08-13T08:28:47Z,NaN,NaN,alexavoiceremoteforamazonechoechodot/b01e9ahu8q,...,5.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I got this great little remote and then spent ...,"Works great, once you read the instructions!",NaN,NaN,T. Masoner,NaN,NaN,4 ounces
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-01-17T16:11:59Z,2017-08-13T08:28:46Z,NaN,NaN,replacementremoteforamazonfiretvstick/b00lorga...,...,2.0,https://www.amazon.com/Replacement-Remote-Amaz...,My remote went out just a couple weeks after w...,Shouldn't have to settle for a Phone App or pa...,NaN,NaN,Rebecca Midwest,NaN,NaN,2.4 ounces
955,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-01-17T16:11:59Z,2017-08-13T08:28:46Z,NaN,NaN,replacementremoteforamazonfiretvstick/b00lorga...,...,2.0,https://www.amazon.com/Replacement-Remote-Amaz...,My remote went out just a couple weeks after w...,Shouldn't have to settle for a Phone App or pa...,NaN,NaN,Rebecca retired Midwest chef,NaN,NaN,2.4 ounces
956,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-01-17T16:11:59Z,2017-08-13T08:28:46Z,NaN,NaN,replacementremoteforamazonfiretvstick/b00lorga...,...,3.0,https://www.amazon.com/Replacement-Remote-Amaz...,It blows my mind theres not a class action law...,Decent replacement for something that shouldnt...,NaN,NaN,Upstate NY SAHM,NaN,NaN,2.4 ounces
957,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-01-17T16:11:59Z,2017-08-13T08:28:46Z,NaN,NaN,replacementremoteforamazonfiretvstick/b00lorga...,...,1.0,https://www.amazon.com/Replacement-Remote-Amaz...,UPDATE: After 3 months of minimal use the remo...,Worked for a while,NaN,NaN,dosiere,NaN,NaN,2.4 ounces
958,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-01-17T16:11:59Z,2017-08-13T08:28:46Z,NaN,NaN,replacementremoteforamazonfiretvstick/b00lorga...,...,4.0,https://www.amazon.com/Replacement-Remote-Amaz...,Remote worked well for about 30 minutes but no...,Disappointed - UPDATE,NaN,NaN,rupert,NaN,NaN,2.4 ounces

In [10]:
columns_to_keep = [
    "id",
    "asins",
    "brand",
    "categories",
    "name",
    "prices",
    "manufacturer",
    "reviews.date",
    "reviews.rating",
    "reviews.text",
    "reviews.title",
    "reviews.username"
]

# Filter the DataFrame
filtered_df = df[columns_to_keep]

# Show sample rows (because we love a good sneak peek 👀)
filtered_df.head()

,id,asins,brand,categories,name,prices,manufacturer,reviews.date,reviews.rating,reviews.text,reviews.title,reviews.username
0,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,2016-05-25T00:00:00.000Z,3.0,Remote is a great addition......I Have two ech...,Remote is a great addition.,BFI66
1,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,2016-05-24T00:00:00.000Z,3.0,The remote seems to function as the previous g...,No Magnetic Holster - But Remote Is Same,Jeffrey C Drywater
2,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,NaN,2.0,"As good as the Echo is, the Echo Voice Remote ...","Has Trouble Understanding Commands, Volume Con...",Jeffrey N. Fritz
3,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,2016-12-28T00:00:00.000Z,1.0,Worked great for a few weeks then completely s...,Dead after 3 weeks,Shain Mercer
4,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,NaN,5.0,I got this great little remote and then spent ...,"Works great, once you read the instructions!",T. Masoner

In [11]:
filtered_df.shape

(959, 12)

In [12]:
filtered_df

,id,asins,brand,categories,name,prices,manufacturer,reviews.date,reviews.rating,reviews.text,reviews.title,reviews.username
0,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,2016-05-25T00:00:00.000Z,3.0,Remote is a great addition......I Have two ech...,Remote is a great addition.,BFI66
1,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,2016-05-24T00:00:00.000Z,3.0,The remote seems to function as the previous g...,No Magnetic Holster - But Remote Is Same,Jeffrey C Drywater
2,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,NaN,2.0,"As good as the Echo is, the Echo Voice Remote ...","Has Trouble Understanding Commands, Volume Con...",Jeffrey N. Fritz
3,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,2016-12-28T00:00:00.000Z,1.0,Worked great for a few weeks then completely s...,Dead after 3 weeks,Shain Mercer
4,AVsRilrqnnc1JgDc34jd,B01E9AHU8Q,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Alexa Voice Remote for Amazon Echo and Echo Dot,29.99,NaN,NaN,5.0,I got this great little remote and then spent ...,"Works great, once you read the instructions!",T. Masoner
...,...,...,...,...,...,...,...,...,...,...,...,...
954,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Replacement Remote for Amazon Fire TV Stick,14.99,NaN,2016-02-02T00:00:00.000Z,2.0,My remote went out just a couple weeks after w...,Shouldn't have to settle for a Phone App or pa...,Rebecca Midwest
955,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Replacement Remote for Amazon Fire TV Stick,14.99,NaN,2016-02-02T00:00:00.000Z,2.0,My remote went out just a couple weeks after w...,Shouldn't have to settle for a Phone App or pa...,Rebecca retired Midwest chef
956,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Replacement Remote for Amazon Fire TV Stick,14.99,NaN,2017-04-01T00:00:00.000Z,3.0,It blows my mind theres not a class action law...,Decent replacement for something that shouldnt...,Upstate NY SAHM
957,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Replacement Remote for Amazon Fire TV Stick,14.99,NaN,2017-02-22T00:00:00.000Z,1.0,UPDATE: After 3 months of minimal use the remo...,Worked for a while,dosiere
958,AVpfODXeilAPnD_xXeUd,B00LORGAG6,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",Replacement Remote for Amazon Fire TV Stick,14.99,NaN,2017-03-17T00:00:00.000Z,4.0,Remote worked well for about 30 minutes but no...,Disappointed - UPDATE,rupert

In [13]:
filtered_df = filtered_df.copy()

In [14]:
filtered_df = filtered_df.copy()  # Clone it like a boss
filtered_df['categories'] = filtered_df['categories'].apply(
    lambda x: ','.join(str(x).split(',')[:3])
)

In [15]:
filtered_df.to_csv("clean_amazon_reviews.csv", index=False)
print("🎉 CSV file saved as 'clean_amazon_reviews.csv'")

🎉 CSV file saved as 'clean_amazon_reviews.csv'

In [16]:
import os
print(os.listdir())

['DataCleanUp.ipynb', '.ipynb_checkpoints', 'clean_amazon_reviews.csv', 'Untitled.ipynb']